// API Endpoints from environment variables
export const API_ENDPOINTS = {
  USERS: process.env.NEXT_INV_USERS || 'http://localhost:8031/users',
  SUPPLIERS: process.env.NEXT_INV_SUPPLIERS || 'http://localhost:8031/suppliers',
  CUSTOMERS: process.env.NEXT_INV_CUSTOMERS || 'http://localhost:8031/customers',
  PRODUCTS: process.env.NEXT_INV_PRODUCTS || 'http://localhost:8031/products',
  PRODUCT_CATEGORIES: process.env.NEXT_INV_PRODUCT_CATEGORIES || 'http://localhost:8031/product_categories',
  UNIT_OF_MEASUREMENTS: process.env.NEXT_INV_UNIT_OF_MEASUREMENTS || 'http://localhost:8031/unit_of_measurements',
  PRODUCT_BATCHES: process.env.NEXT_INV_PRODUCT_BATCHES || 'http://localhost:8031/product_batches',
  COMPANIES: process.env.NEXT_INV_COMPANIES || 'http://localhost:8031/companies',
  ROLES: process.env.NEXT_INV_ROLES || 'http://localhost:8031/roles',
  INVOICES: process.env.NEXT_INV_INVOICES || 'http://localhost:8031/invoices',
  INVOICE_ITEMS: process.env.NEXT_INV_INVOICE_ITEMS || 'http://localhost:8031/invoice_items',
  INVOICE_SUMMARY: process.env.NEXT_INV_INVOICE_SUMMARY || 'http://localhost:8031/invoice_summary',
  OUTSTANDING_INVOICES: process.env.NEXT_INV_OUTSTANDING_INVOICES || 'http://localhost:8031/outstanding_invoices',
  PAYMENTS: process.env.NEXT_INV_PAYMENTS || 'http://localhost:8031/payments',
  TAX_RATES: process.env.NEXT_INV_TAX_RATES || 'http://localhost:8031/tax_rates',
  STOCK_LEVELS: process.env.NEXT_INV_STOCK_LEVELS || 'http://localhost:8031/stock_levels',
  STOCK_TRANSACTIONS: process.env.NEXT_INV_STOCK_TRANSACTIONS || 'http://localhost:8031/stock_transactions',
  LOW_STOCK_PRODUCTS: process.env.NEXT_INV_LOW_STOCK_PRODUCTS || 'http://localhost:8031/low_stock_products',
  NOTIFICATIONS: process.env.NEXT_INV_NOTIFICATIONS || 'http://localhost:8031/notifications',
  AUDIT_LOGS: process.env.NEXT_INV_AUDIT_LOGS || 'http://localhost:8031/audit_logs',
  USER_SESSIONS: process.env.NEXT_INV_USER_SESSIONS || 'http://localhost:8031/user_sessions',
  WAREHOUSES: process.env.NEXT_INV_WAREHOUSES || 'http://localhost:8031/warehouses',
  PURCHASE_ORDERS: process.env.NEXT_INV_PURCHASE_ORDERS || 'http://localhost:8031/purchase_orders',
  PURCHASE_ORDER_ITEMS: process.env.NEXT_INV_PURCHASE_ORDER_ITEMS || 'http://localhost:8031/purchase_order_items',
  STOCK_TRANSFERS: process.env.NEXT_INV_STOCK_TRANSFERS || 'http://localhost:8031/stock_transfers',
  STOCK_TRANSFER_ITEMS: process.env.NEXT_INV_STOCK_TRANSFER_ITEMS || 'http://localhost:8031/stock_transfer_items',
  BIN_LOCATIONS: process.env.NEXT_INV_BIN_LOCATIONS || 'http://localhost:8031/bin_locations',
  BIN_STOCK: process.env.NEXT_INV_BIN_STOCK || 'http://localhost:8031/bin_stock',
  SALES_ORDERS: process.env.NEXT_INV_SALES_ORDERS || 'http://localhost:8031/sales_orders',
  SALES_ORDER_ITEMS: process.env.NEXT_INV_SALES_ORDER_ITEMS || 'http://localhost:8031/sales_order_items',
  GRN: process.env.NEXT_INV_GRN || 'http://localhost:8031/grn',
  GRN_ITEMS: process.env.NEXT_INV_GRN_ITEMS || 'http://localhost:8031/grn_items',
  WAREHOUSE_CAPACITY_OVERVIEW: process.env.NEXT_INV_WAREHOUSE_CAPACITY_OVERVIEW || 'http://localhost:8031/warehouse_capacity_overview',
  PRODUCT_BIN_DISTRIBUTION: process.env.NEXT_INV_PRODUCT_BIN_DISTRIBUTION || 'http://localhost:8031/product_bin_distribution',
  AVAILABLE_BINS: process.env.NEXT_INV_AVAILABLE_BINS || 'http://localhost:8031/available_bins',
  PRODUCT_TYPES: process.env.NEXT_INV_PRODUCT_TYPES || 'http://localhost:8031/product_types',
  WARRANTY_TYPES: process.env.NEXT_INV_WARRANTY_TYPES || 'http://localhost:8031/warranty_types',
  SHELF_LIFE_CATEGORIES: process.env.NEXT_INV_SHELF_LIFE_CATEGORIES || 'http://localhost:8031/shelf_life_categories',
  BRANDS: process.env.NEXT_INV_BRANDS || 'http://localhost:8031/brands',
  HANDLING_INSTRUCTIONS: process.env.NEXT_INV_HANDLING_INSTRUCTIONS || 'http://localhost:8031/handling_instructions',
  COMPANY_EMAIL_SETTINGS: process.env.NEXT_INV_COMPANY_EMAIL_SETTINGS || 'http://localhost:8031/company_email_settings',
  USER_WAREHOUSES: process.env.NEXT_INV_USER_WAREHOUSES || 'http://localhost:8031/user_warehouses',
  // Production workflow
  MATERIAL_REQUESTS: process.env.NEXT_INV_MATERIAL_REQUESTS || 'http://localhost:8035/material_requests',
  MATERIAL_REQUEST_ITEMS: process.env.NEXT_INV_MATERIAL_REQUEST_ITEMS || 'http://localhost:8035/material_request_items',
  JOB_ORDERS: process.env.NEXT_INV_JOB_ORDERS || 'http://localhost:8035/job_orders',
  JOB_ORDER_BOM: process.env.NEXT_INV_JOB_ORDER_BOM || 'http://localhost:8035/job_order_bom',
  JOB_ORDER_BOM_REQUESTS: process.env.NEXT_INV_JOB_ORDER_BOM_REQUESTS || 'http://localhost:8035/job_order_bom_requests',
  MATERIAL_ISSUE_SLIPS: process.env.NEXT_INV_MATERIAL_ISSUE_SLIPS || 'http://localhost:8035/material_issue_slips',
  MATERIAL_ISSUE_SLIP_ITEMS: process.env.NEXT_INV_MATERIAL_ISSUE_SLIP_ITEMS || 'http://localhost:8035/material_issue_slip_items',
  MATERIAL_RETURN_SLIPS: process.env.NEXT_INV_MATERIAL_RETURN_SLIPS || 'http://localhost:8035/material_return_slips',
  MATERIAL_RETURN_SLIP_ITEMS: process.env.NEXT_INV_MATERIAL_RETURN_SLIP_ITEMS || 'http://localhost:8035/material_return_slip_items',
};

if (!process.env.POSTGREST_API_KEY) {
  console.error('[CONFIG] POSTGREST_API_KEY is not set. API calls will fail.');
}
export const API_KEY = process.env.POSTGREST_API_KEY ?? '';
