// API Endpoints from environment variables
const BASE = process.env.POSTGREST_URL || 'http://localhost:8036';

export const API_ENDPOINTS = {
  USERS:                      process.env.NEXT_INV_USERS                      || `${BASE}/users`,
  SUPPLIERS:                  process.env.NEXT_INV_SUPPLIERS                  || `${BASE}/suppliers`,
  CUSTOMERS:                  process.env.NEXT_INV_CUSTOMERS                  || `${BASE}/customers`,
  PRODUCTS:                   process.env.NEXT_INV_PRODUCTS                   || `${BASE}/products`,
  PRODUCT_CATEGORIES:         process.env.NEXT_INV_PRODUCT_CATEGORIES         || `${BASE}/product_categories`,
  UNIT_OF_MEASUREMENTS:       process.env.NEXT_INV_UNIT_OF_MEASUREMENTS       || `${BASE}/unit_of_measurements`,
  PRODUCT_BATCHES:            process.env.NEXT_INV_PRODUCT_BATCHES            || `${BASE}/product_batches`,
  COMPANIES:                  process.env.NEXT_INV_COMPANIES                  || `${BASE}/companies`,
  ROLES:                      process.env.NEXT_INV_ROLES                      || `${BASE}/roles`,
  INVOICES:                   process.env.NEXT_INV_INVOICES                   || `${BASE}/invoices`,
  INVOICE_ITEMS:              process.env.NEXT_INV_INVOICE_ITEMS              || `${BASE}/invoice_items`,
  INVOICE_SUMMARY:            process.env.NEXT_INV_INVOICE_SUMMARY            || `${BASE}/invoice_summary`,
  OUTSTANDING_INVOICES:       process.env.NEXT_INV_OUTSTANDING_INVOICES       || `${BASE}/outstanding_invoices`,
  PAYMENTS:                   process.env.NEXT_INV_PAYMENTS                   || `${BASE}/payments`,
  TAX_RATES:                  process.env.NEXT_INV_TAX_RATES                  || `${BASE}/tax_rates`,
  STOCK_LEVELS:               process.env.NEXT_INV_STOCK_LEVELS               || `${BASE}/stock_levels`,
  STOCK_TRANSACTIONS:         process.env.NEXT_INV_STOCK_TRANSACTIONS         || `${BASE}/stock_transactions`,
  LOW_STOCK_PRODUCTS:         process.env.NEXT_INV_LOW_STOCK_PRODUCTS         || `${BASE}/low_stock_products`,
  NOTIFICATIONS:              process.env.NEXT_INV_NOTIFICATIONS              || `${BASE}/notifications`,
  AUDIT_LOGS:                 process.env.NEXT_INV_AUDIT_LOGS                 || `${BASE}/audit_logs`,
  USER_SESSIONS:              process.env.NEXT_INV_USER_SESSIONS              || `${BASE}/user_sessions`,
  WAREHOUSES:                 process.env.NEXT_INV_WAREHOUSES                 || `${BASE}/warehouses`,
  USER_WAREHOUSES:            process.env.NEXT_INV_USER_WAREHOUSES            || `${BASE}/user_warehouses`,
  PURCHASE_ORDERS:            process.env.NEXT_INV_PURCHASE_ORDERS            || `${BASE}/purchase_orders`,
  PURCHASE_ORDER_ITEMS:       process.env.NEXT_INV_PURCHASE_ORDER_ITEMS       || `${BASE}/purchase_order_items`,
  STOCK_TRANSFERS:            process.env.NEXT_INV_STOCK_TRANSFERS            || `${BASE}/stock_transfers`,
  STOCK_TRANSFER_ITEMS:       process.env.NEXT_INV_STOCK_TRANSFER_ITEMS       || `${BASE}/stock_transfer_items`,
  BIN_LOCATIONS:              process.env.NEXT_INV_BIN_LOCATIONS              || `${BASE}/bin_locations`,
  BIN_STOCK:                  process.env.NEXT_INV_BIN_STOCK                  || `${BASE}/bin_stock`,
  SALES_ORDERS:               process.env.NEXT_INV_SALES_ORDERS               || `${BASE}/sales_orders`,
  SALES_ORDER_ITEMS:          process.env.NEXT_INV_SALES_ORDER_ITEMS          || `${BASE}/sales_order_items`,
  GRN:                        process.env.NEXT_INV_GRN                        || `${BASE}/grn`,
  GRN_ITEMS:                  process.env.NEXT_INV_GRN_ITEMS                  || `${BASE}/grn_items`,
  WAREHOUSE_CAPACITY_OVERVIEW:process.env.NEXT_INV_WAREHOUSE_CAPACITY_OVERVIEW|| `${BASE}/warehouse_capacity_overview`,
  PRODUCT_BIN_DISTRIBUTION:   process.env.NEXT_INV_PRODUCT_BIN_DISTRIBUTION   || `${BASE}/product_bin_distribution`,
  AVAILABLE_BINS:             process.env.NEXT_INV_AVAILABLE_BINS             || `${BASE}/available_bins`,
  PRODUCT_TYPES:              process.env.NEXT_INV_PRODUCT_TYPES              || `${BASE}/product_types`,
  WARRANTY_TYPES:             process.env.NEXT_INV_WARRANTY_TYPES             || `${BASE}/warranty_types`,
  SHELF_LIFE_CATEGORIES:      process.env.NEXT_INV_SHELF_LIFE_CATEGORIES      || `${BASE}/shelf_life_categories`,
  BRANDS:                     process.env.NEXT_INV_BRANDS                     || `${BASE}/brands`,
  HANDLING_INSTRUCTIONS:      process.env.NEXT_INV_HANDLING_INSTRUCTIONS      || `${BASE}/handling_instructions`,
  COMPANY_EMAIL_SETTINGS:     process.env.NEXT_INV_COMPANY_EMAIL_SETTINGS     || `${BASE}/company_email_settings`,
  MATERIAL_REQUESTS:          process.env.NEXT_INV_MATERIAL_REQUESTS          || `${BASE}/material_requests`,
  MATERIAL_REQUEST_ITEMS:     process.env.NEXT_INV_MATERIAL_REQUEST_ITEMS     || `${BASE}/material_request_items`,
  JOB_ORDERS:                 process.env.NEXT_INV_JOB_ORDERS                 || `${BASE}/job_orders`,
  JOB_ORDER_BOM:              process.env.NEXT_INV_JOB_ORDER_BOM              || `${BASE}/job_order_bom`,
  JOB_ORDER_BOM_REQUESTS:     process.env.NEXT_INV_JOB_ORDER_BOM_REQUESTS     || `${BASE}/job_order_bom_requests`,
  MATERIAL_ISSUE_SLIPS:       process.env.NEXT_INV_MATERIAL_ISSUE_SLIPS       || `${BASE}/material_issue_slips`,
  MATERIAL_ISSUE_SLIP_ITEMS:  process.env.NEXT_INV_MATERIAL_ISSUE_SLIP_ITEMS  || `${BASE}/material_issue_slip_items`,
  MATERIAL_RETURN_SLIPS:      process.env.NEXT_INV_MATERIAL_RETURN_SLIPS      || `${BASE}/material_return_slips`,
  MATERIAL_RETURN_SLIP_ITEMS: process.env.NEXT_INV_MATERIAL_RETURN_SLIP_ITEMS || `${BASE}/material_return_slip_items`,
};

if (!process.env.POSTGREST_API_KEY) {
  console.error('[CONFIG] POSTGREST_API_KEY is not set. API calls will fail.');
}
export const API_KEY = process.env.POSTGREST_API_KEY ?? '';
